### PR TITLE
Add token, repo and sha input

### PR DESCRIPTION
**Pull request by n-elie**
This would allow this action to be used to create a release on a different repository it is being run from

### CODE REVIEW

**Review by WebFreak001 — APPROVED** [review]

**Comment by WebFreak001** [comment]
ah I tested it in master now and it seems to work, but I think I will revert this again, since with the previous way it was already possible to customize, just through `env` instead of through `with`

Since the values here are kinda internal, I don't think it's actually that good to expose it this publicly.

Instead use this as workaround:

```yml
      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
          GITHUB_SHA: 547fdf5 # optional, a commit SHA
          GITHUB_REPOSITORY: Pure-D/serve-d # optional, the repository where the release is located
        with:
          upload_url: https://uploads.github.com/repos/Pure-D/serve-d/releases/20717582/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
          release_id: 20717582 # same as above (id can just be taken out the upload_url, it's used to find old releases)
          asset_path: ./myapp.zip # path to archive to upload
          asset_name: myapp_windows-nightly-$$.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
          asset_content_type: application/zip # required by GitHub API
          max_releases: 7 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
```

**Comment by n-elie** [comment]
Actually, I tried setting environments variables but this didn't work. Github token is not overwritten and default token is not able to write to other repository than the one it is generated from.
See here for example: https://github.com/metgem/metgem_releases/actions/runs/6628777148/job/18006627748#step:11:18
The action ends with `Error: Not Found`

**Comment by WebFreak001** [comment]
oh right sorry, I didn't actually test it, but it would make sense that github blocks settings these values.

Let's go with your implementation then after all, I'll just rephrase the README a little bit, since this is a rather niche use-case

**Comment by WebFreak001** [comment]
are you sure `GITHUB_TOKEN` is not changable? I added it to the README, so I think I probably had issues without explicitly providing it before and it wouldn't make sense to keep it in there if it's not overridable

**Pull request merged**
