### PR TITLE
Fixed a bug in old assets deletion.

### PR DESCRIPTION
**Pull request by Maxzor**
yes
well actually you might want to pull from simontom

### CODE REVIEW

**Comment by WebFreak001** [comment]
with what data did the bug happen? There is no advantage in comparing string literals, it only adds bugs in case of stuff like DST changes or different timezones. If it was some undefined/null issue, that should be handled instead of being obfuscated by string comparision (where it would currently also crash in case of a null a.created_at)

**Comment by Maxzor** [comment]
You compare how you want, but currently the newest versions are deleted, not the oldest

**Comment by WebFreak001** [comment]
you are right, thanks for noticing that

**Comment by Maxzor** [comment]
np!
simontom is a bad guy he diverged, fixed it your way(if Date() does the job actually), and did not upstream
https://github.com/simontom/deploy-nightly

**Comment by WebFreak001** [comment]
for discussion about these changes see #4, I decided not to take these changes as-is because I did not agree with the API design, but I haven't gotten around to implement it myself yet.

**Pull request closed without merging**
